### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by nnelson96** [zerokol/JoystickView#4]
Inside the onTouchEvent, for 
if (event.getAction() == MotionEvent.ACTION_UP)
why do you do this:
xPosition = (int) centerX;
yPosition = (int) centerY;

what exactly does that do and why dont you have the same thing for ACTION_DOWN?

**Comment by zerokol** [comment]
This code recenter the joystick red button, it happens only in the action up that is when the user release its finger from screen.
